[versions]
agp = "8.8.0"
disklrucache = "2.0.2"
gson = "2.10.1"
jsoup = "1.18.3"
leanback = "1.0.0"
glide = "4.11.0"
appcompat = "1.7.0"
okhttp = "4.12.0"

[libraries]
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
disklrucache = { module = "com.jakewharton:disklrucache", version.ref = "disklrucache" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

